version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "${VITE_APP_PORT}:${VITE_APP_PORT}"  # Usa a variável
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: yarn dev --port ${VITE_APP_PORT}